### ISSUE TITLE
jwt assertion client migration ends with error

### ISSUE THREAD

**Issue by bgirts** [curityio/database-client-migration-example#14]
Jwt assertion client migration ends in error, though there actually is RSA key in the source. 

file:///C:/work/repos/ah/Curity.DbClientMigration/database-client-migration-example/src/graphqlClient.ts:135
            throw new Error(errorText);
                  ^
```
Error: , Asymmetric signing key must be an RSA key
    at GraphqlClient.saveClient (file:///C:/work/repos/ah/Curity.DbClientMigration/database-client-migration-example/src/graphqlClient.ts:135:19)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async file:///C:/work/repos/ah/Curity.DbClientMigration/database-client-migration-example/src/index.ts:39:17
```
```    
   Source xml:
   <config xmlns="http://tail-f.com/ns/config/1.0">
    <profiles xmlns="https://curity.se/ns/conf/base">
    <profile>
    <id>token-service</id>
    <type xmlns:as="https://curity.se/ns/conf/profile/oauth">as:oauth-service</type>
      <settings>
      <authorization-server xmlns="https://curity.se/ns/conf/profile/oauth">
      <client-store>
      <config-backed>
      <client>
        <id>1b9ca44b-47e4-482f-8e86-5ff54759be37</id>
        <client-name>Client name</client-name>
        <description>Description</description>
        <secret>****</secret>
        <access-token-ttl>3000</access-token-ttl>
        <scope>***</scope>
        <capabilities>
          <client-credentials/>
          <assertion>
            <jwt>
              <trust>
                <asymmetric-signing-key>***_management_assertion</asymmetric-signing-key>
              </trust>
            </jwt>
          </assertion>
        </capabilities>
        <use-pairwise-subject-identifiers>
          <sector-identifier>6ec1f601-5e14-4db0-ba95-869469f81001</sector-identifier>
        </use-pairwise-subject-identifiers>
        <properties>
          <property>
            <key>***</key>
            <value>***</value>
          </property>
        </properties>
      </client>
      </config-backed>
      </client-store>
      </authorization-server>
      </settings>
  </profile>
  </profiles>
</config>
```

**Comment by bgirts** [comment]
False positive due to error message. Actually the key was not in the destination environment.
